### PR TITLE
Fix response headers

### PR DESCRIPTION
**Pull request by janraasch**
Since `HttpStreamingResponse#headers` returns a `HeaderHash` with `Array`-keys,
e.g.

```ruby
    {"cache-control"=>["max-age=300, public"]}
```

we need to normalise this to something like

```ruby
    {"cache-control"=> "max-age=300, public"}
```

in order to **not break other middlewares** processing the headers further down the pipe.

In our case we encountered a problem when working with `rack-wwwhisper`,
see `Rack::WWWhisper::NoPublicCache#call` (https://github.com/wrr/rack-wwwhisper),
since it tries to call `.gsub` on the `'Cache-Control'`-header.

While at it, I reused some more methods from the `rack-proxy` gem, and added a `.travis.yml` to run tests on ruby  `1.9.3`, `2.0.0` and `2.1.2`.

### CODE REVIEW

**Comment by kurotaky** [comment]
:+1:

**Comment by waterlink** [comment]
Looks good. I will cherry-pick first 2 commits on top of https://github.com/waterlink/rack-reverse-proxy (new main repo). It already has proper `.travis.yml` file.

**Comment by waterlink** [comment]
Merged here: https://github.com/waterlink/rack-reverse-proxy/pull/6

**Comment by janraasch** [comment]
@waterlink merci. :+1:

**Pull request closed without merging**
